### ISSUE TITLE
Deploy to addons.mozilla.org

### ISSUE THREAD

**Issue by indeyets** [davidmz/share-on-freefeed-ext#2]
Firefox's addons are switching to WebExtension technology right now.

I followed [this guide](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension) and it looks like extension just works without any changes

**Comment by davidmz** [comment]
Done!
https://addons.mozilla.org/ru/firefox/addon/share-links-on-freefeed/
